<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<link rel="stylesheet" href="http://refineddesigns.net//proto/css/bootstrap.css" type="text/css" media="screen">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/eggplant/jquery-ui.css" type="text/css" media="screen">
<link rel="stylesheet" href="css/global.css" type="text/css" media="screen">
<title>Admin P</title>
</head>
<body>

  