			<div class="navbar navbar-inverse"><!--Start of Navbar-->
			
				<h1>
					<a href="../index.php"><img alt="Holton Street Autobody" src="../img/logo.gif" class="header">
					</a>			
				</h1>

				<div class="navbar-inner">
					<div class="container">
			 
						<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
						<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>
			 
							<!-- Everything you want hidden at 940px or less, place within here -->
						<div class="nav-collapse collapse">
							<!-- .nav, .navbar-search, .navbar-form, etc -->
							<ul class="nav">
								<li><a href="../index.php">Home</a></li>
								<li><a href="../about.php">About</a></li>
								<li><a href="../insurance.php">Insurance</a></li>
								<li><a href="../testimonials.php">Testimonials</a></li>
								<li class="dropdown navsplit">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										Water Transfer Process
										<b class="caret"></b>
									</a>
									
									<ul class="dropdown-menu">
										<li><a href="../wtAbout.php">About</a></li>
										<li><a href="../wtPatterns.php">Patterns</a></li>
									</ul>
								</li>
								<li class="active"><a href="index.php">Portal</a></li>
					
							</ul>
						</div>
			 
					</div>
				</div>
			</div><!--End of Navbar-->
		
	
		
		<div id="portal" class="row">
			<div class="span6"><!--span6-->
				<span class="span-margin">
				<h2>The Portal</h2>
				
				<p> Imagine yourself being able to log in after choosing Holton Street Auto Body, and seeing exactly how far your car or other project is coming along, with Holton Street's Portal you can!</p>
				
				<p>
					After choosing Holton Street Auto Body, you will have the option to choose to sign up for the portal.
				</p>
				
				<p>
					If you choose so you will sign in here, or use the login button on any of the other pages.
				</p>
				</span>					
			</div><!--end span6-->
			
			<div class="span6"><!--span6-->
				<span class="span-margin">
					<h2>Login</h2>
				
					<form method="post" action="?" class="form-horizontal">
						<div class="control-group">
							<label class="control-label" for="inputEmail">Email</label>
							<div class="controls">
								<input type="text" name="username" id="username" placeholder="Email">
							</div>
						</div>
						
						<div class="control-group">
							<label class="control-label" for="inputPassword">Password</label>
							<div class="controls">
								<input type="password" name="password" id="password" placeholder="Password">
							</div>
						</div>
						
						<div class="control-group">
							<div class="controls">
								<button name="submit" type="submit" class="btn btn-info">Sign in</button>
							</div>
							
						</div>
					</form>
					
				</span>
			</div><!--end span6-->
		</div><!--end Rows-->
