<!DOCTYPE html>
<html>
	<head>
		<title>Holton Street</title>
		<link rel="icon" type="image/png" href="../img/favicon.ico">		
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
			
		<!---- CSS ------->
		<link rel="stylesheet" href="../css/bootstrap.css" type="text/css" media="screen">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/dark-hive/jquery-ui.css" type="text/css" media="screen">
		<link rel="stylesheet" href="../css/global.css" type="text/css" media="screen">	
		<link rel="stylesheet" type="text/css" href="../css/prettyPhoto.css">
	</head>
	<body>
	
		<div class="container"><!--Start of container-->
